@startuml Macowins

class Prenda {
  precioBase
  tipo
  precioFinal()
}

class EstadoPrenda {
  aplicar(precio)
}

class Nueva

class Promocion {
  descuento
}
class Liquidacion

EstadoPrenda <|-- Nueva
EstadoPrenda <|-- Promocion
EstadoPrenda <|-- Liquidacion

class Venta {
  fecha
  total()
}

class ItemVenta {
  cantidad
  subtotal()
}

class TipoPago {
  recargo(total)
}

class Efectivo
class Tarjeta {
  cuotas
  coeficiente
}

Venta --> TipoPago

Venta --> ItemVenta

ItemVenta --> Prenda

Prenda --> EstadoPrenda

TipoPago <|-- Efectivo

TipoPago <|-- Tarjeta



@enduml